### ISSUE TITLE
Change structure of nextsim docker images

### ISSUE THREAD

**Issue by akorosov** [nansencenter/docker-nextsim-base#11]
# New structure (linear)

#### Production
* from ubuntu:bionic
* minimal apt libs
* boost (use builder image with gcc, etc)
* pets
* gmsh
* minimal packaged conda  environment (use continium/miniconda to build and pack, move here some packages from docker-boost-petsc-gmsh-conda)

#### Development
* from continuum:miniconda
* all apt libs (move all apt libs from nextsim here)
* boost
* pets
* gmsh
* full conda environment (move here from docker-boost-petsc-gmsh-conda)

### nextsim
* from docker-nextsim-base (either dev or pro)
* bamg
* mapx
* nextsim (installed in image)

### nextsim-tools
* from nextsim  (either dev or pro)
* mapx
* bamg
* pynextsim (installed in image)

### nextsimf
* from nextsim-tools (either dev or pro)
* pynextsimf

### nextsim-env
* from nextsimf (either dev or pro)
* configuration
* download scripts

# Actions:

## docker-nextsim-base

* rename docker-nextsim-base

### Production
* Move as few apt libs from nextsim
* Update Dockerfile to run in one go (replace `FROM boos_pets_gmsh:base with `FROM base`
* Add minimal conda env using packaging

### Development
* Move all apt libs from nextsim
* Update Dockerfile to run in one go (replace `FROM boos_pets_gmsh:base with `FROM base`
* Add all libs from docker-boost-petsc-gmsh-conda

## nextsim
* install nextsim inside image
* make sure locally compiled nextsim can also run

## nextsim-tools
* install pynextsim inside image

## nextsimf
* install pynextsimf inside image

## nextsim-env
* Add Dockerfile

**Comment by tdcwilliams** [comment]
Perhaps another layer could be added which would be like the nextsim-tools image now:  `nextsim-tools-base` with conda + bamg, mapx python wrappers? This could be more for developers of the different codes, so they can change the source more easily.
